application: okyasoft
version: 1-0
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /images/(.*) 
  static_files: static/images/\1 
  upload: static/images/(.*)

- url: /css/(.*) 
  static_files: static/css/\1 
  upload: static/css/(.*)

- url: /resources/(.*) 
  static_files: static/resources/\1 
  upload: static/resources/(.*)

- url: /css/5grid(.*) 
  static_files: static/css/5grid\1 
  upload: static/css/5grid(.*)

- url: /css/images(.*) 
  static_files: static/css/images\1 
  upload: static/css/images(.*)

- url: /js/(.*) 
  static_files: static/js/\1 
  upload: static/js/(.*)

- url: /(.*\.html) 
  static_files: static/\1 
  upload: static/(.*\.html)

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /
  static_files: static/index.html
  upload: static/index.html